-- PrMO — Schema autoritativo aplicado no Supabase (projeto prmo-governanca / ref ubixfcoigwpjdrioymdq).
-- Gerado a partir de Base.metadata.create_all do backend (SQLAlchemy) e aplicado via
-- migração `prmo_initial_schema`. PKs em IDENTITY (compatível com inserts do backend e
-- com carga de dados com id explícito). RLS é ativado à parte (migração
-- `prmo_reset_identity_and_enable_rls`) — ver docs/SUPABASE.md §6.

CREATE TYPE public.skilllevel AS ENUM ('Iniciante','Intermediário','Avançado','Especialista');
CREATE TYPE public.toolstatus AS ENUM ('Ativa','Manutenção','Desativada');
CREATE TYPE public.userrole AS ENUM ('Admin','Manager','User');
CREATE TYPE public.userstatus AS ENUM ('Ativo','Inativo');

CREATE TABLE public.activities (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action character varying(200) NOT NULL,
    "user" character varying(120) NOT NULL,
    user_id integer,
    date character varying(10) NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(120) NOT NULL,
    email character varying(120) NOT NULL,
    hashed_password character varying(255) NOT NULL,
    role public.userrole NOT NULL,
    status public.userstatus NOT NULL,
    is_superuser boolean,
    last_access character varying(10),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone
);

CREATE TABLE public.audit_logs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "timestamp" timestamp with time zone DEFAULT now() NOT NULL,
    user_id integer,
    user_email character varying(120),
    action character varying(100) NOT NULL,
    resource_type character varying(50) NOT NULL,
    resource_id integer,
    details text,
    ip_address character varying(45),
    user_agent character varying(500),
    success boolean,
    error_message text
);

CREATE TABLE public.gov_adoption (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area character varying(120) NOT NULL,
    percent integer,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.gov_clients (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(160) NOT NULL,
    segment character varying(160),
    squad character varying(80),
    ai_usage character varying(80),
    brand_safety character varying(120),
    responsible character varying(120),
    stage character varying(20),
    flows integer,
    playbook_active boolean,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.gov_cost_policy (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_cost_per_call double precision,
    currency character varying(8),
    updated_by character varying(120),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.gov_incidents (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title character varying(200) NOT NULL,
    area character varying(120),
    criticality character varying(20),
    status character varying(30),
    description text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.gov_initiatives (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(200) NOT NULL,
    area character varying(200),
    status character varying(40),
    hours_saved integer,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.gov_prompts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title character varying(200) NOT NULL,
    description character varying(400),
    area character varying(60),
    control character varying(30),
    content text,
    repo_url character varying(300),
    cost_per_call double precision,
    last_review character varying(30),
    uses integer,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.gov_registry (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registry character varying(30),
    code character varying(255),
    data text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.gov_skills (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area character varying(120) NOT NULL,
    description character varying(240),
    level character varying(30),
    reviewer character varying(120),
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.gov_stack_tools (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(160) NOT NULL,
    description character varying(240),
    status character varying(30),
    request_code character varying(40),
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.gov_training (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(160) NOT NULL,
    percent integer,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.integration_configs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(50) NOT NULL UNIQUE,
    display_name character varying(100) NOT NULL,
    is_enabled boolean,
    config text,
    last_sync timestamp with time zone,
    last_sync_status character varying(20),
    last_sync_error text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone
);

CREATE TABLE public.integration_sync_logs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integration_id integer NOT NULL REFERENCES public.integration_configs(id),
    sync_type character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    records_processed integer,
    records_created integer,
    records_updated integer,
    records_failed integer,
    error_details text,
    started_at timestamp with time zone DEFAULT now(),
    completed_at timestamp with time zone,
    duration_seconds integer
);

CREATE TABLE public.prompts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title character varying(200) NOT NULL,
    category character varying(60) NOT NULL,
    text text NOT NULL,
    uses integer,
    is_favorite boolean,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone
);

CREATE TABLE public.skills (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team character varying(60) NOT NULL,
    skill character varying(120) NOT NULL,
    category character varying(60) NOT NULL,
    level public.skilllevel NOT NULL,
    reviewer character varying(120),
    reviewer_id integer REFERENCES public.users(id),
    updated_date character varying(10),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone
);

CREATE TABLE public.tools (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(120) NOT NULL,
    category character varying(60) NOT NULL,
    team character varying(60) NOT NULL,
    status public.toolstatus NOT NULL,
    acquisition_date character varying(10),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone
);

ALTER TABLE public.activities ADD CONSTRAINT activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE public.audit_logs ADD CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);

CREATE INDEX ix_activities_id ON public.activities USING btree (id);
CREATE INDEX ix_audit_logs_action ON public.audit_logs USING btree (action);
CREATE INDEX ix_audit_logs_id ON public.audit_logs USING btree (id);
CREATE INDEX ix_audit_logs_resource_id ON public.audit_logs USING btree (resource_id);
CREATE INDEX ix_audit_logs_resource_type ON public.audit_logs USING btree (resource_type);
CREATE INDEX ix_audit_timestamp_action ON public.audit_logs USING btree ("timestamp", action);
CREATE INDEX ix_audit_user_resource ON public.audit_logs USING btree (user_id, resource_type);
CREATE INDEX ix_gov_adoption_id ON public.gov_adoption USING btree (id);
CREATE INDEX ix_gov_clients_id ON public.gov_clients USING btree (id);
CREATE INDEX ix_gov_cost_policy_id ON public.gov_cost_policy USING btree (id);
CREATE INDEX ix_gov_incidents_id ON public.gov_incidents USING btree (id);
CREATE INDEX ix_gov_initiatives_id ON public.gov_initiatives USING btree (id);
CREATE INDEX ix_gov_prompts_id ON public.gov_prompts USING btree (id);
CREATE INDEX ix_gov_registry_id ON public.gov_registry USING btree (id);
CREATE INDEX ix_gov_registry_registry ON public.gov_registry USING btree (registry);
CREATE INDEX ix_gov_skills_id ON public.gov_skills USING btree (id);
CREATE INDEX ix_gov_stack_tools_id ON public.gov_stack_tools USING btree (id);
CREATE INDEX ix_gov_training_id ON public.gov_training USING btree (id);
CREATE INDEX ix_integration_configs_id ON public.integration_configs USING btree (id);
CREATE INDEX ix_integration_sync_logs_id ON public.integration_sync_logs USING btree (id);
CREATE INDEX ix_prompts_category ON public.prompts USING btree (category);
CREATE INDEX ix_prompts_id ON public.prompts USING btree (id);
CREATE INDEX ix_skills_id ON public.skills USING btree (id);
CREATE INDEX ix_skills_team ON public.skills USING btree (team);
CREATE INDEX ix_tools_id ON public.tools USING btree (id);
CREATE UNIQUE INDEX ix_users_email ON public.users USING btree (email);
CREATE INDEX ix_users_id ON public.users USING btree (id);

CREATE TABLE public.gov_support (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind character varying(30) DEFAULT 'Solicitação',
    subject character varying(200) NOT NULL,
    area character varying(120) DEFAULT '',
    severity character varying(20) DEFAULT 'Média',
    message text DEFAULT '',
    requester character varying(120) DEFAULT '',
    requester_email character varying(120) DEFAULT '',
    status character varying(30) DEFAULT 'Aberto',
    response text DEFAULT '',
    handled_by character varying(120) DEFAULT '',
    handled_at character varying(30) DEFAULT '',
    created_at timestamp with time zone DEFAULT now()
);
CREATE INDEX ix_gov_support_id ON public.gov_support USING btree (id);
CREATE INDEX ix_gov_support_requester_email ON public.gov_support USING btree (requester_email);

CREATE TABLE public.gov_asset_requests (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(200) NOT NULL,
    features text DEFAULT '',
    url character varying(300) DEFAULT '',
    repo_url character varying(300) DEFAULT '',
    repo_scope character varying(20) DEFAULT 'Público',
    requester character varying(120) DEFAULT '',
    requester_email character varying(120) DEFAULT '',
    status character varying(20) DEFAULT 'Pendente',
    review_note text DEFAULT '',
    handled_by character varying(120) DEFAULT '',
    handled_at character varying(30) DEFAULT '',
    created_at timestamp with time zone DEFAULT now()
);
CREATE INDEX ix_gov_asset_requests_id ON public.gov_asset_requests USING btree (id);
CREATE INDEX ix_gov_asset_requests_requester_email ON public.gov_asset_requests USING btree (requester_email);

CREATE TABLE public.gov_suggestions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(40) DEFAULT '',
    title character varying(200) NOT NULL,
    area character varying(120) DEFAULT '',
    ptype character varying(1) DEFAULT '',
    message text DEFAULT '',
    source character varying(30) DEFAULT 'Colaborador',
    author character varying(120) DEFAULT '',
    requester_email character varying(120) DEFAULT '',
    status character varying(20) DEFAULT 'Nova',
    note text DEFAULT '',
    handled_by character varying(120) DEFAULT '',
    handled_at character varying(30) DEFAULT '',
    created_at timestamp with time zone DEFAULT now()
);
CREATE INDEX ix_gov_suggestions_id ON public.gov_suggestions USING btree (id);
CREATE INDEX ix_gov_suggestions_source ON public.gov_suggestions USING btree (source);
CREATE INDEX ix_gov_suggestions_requester_email ON public.gov_suggestions USING btree (requester_email);

-- Base de Conhecimento (cursos/trilhas estilo Udemy) e progresso por aluno.
CREATE TABLE public.gov_courses (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(40) DEFAULT '',
    title character varying(200) NOT NULL,
    description text DEFAULT '',
    category character varying(40) DEFAULT 'IA',          -- IA | Compliance | Segurança da Informação
    level character varying(20) DEFAULT 'Iniciante',      -- Iniciante | Intermediário | Avançado
    instructor character varying(120) DEFAULT '',
    cover character varying(8) DEFAULT '🎓',
    accent character varying(9) DEFAULT '#6d28d9',
    duration_min integer DEFAULT 0,
    tags character varying(240) DEFAULT '',
    lessons text DEFAULT '[]',                            -- JSON: [{title,type,duration_min,url}]
    published boolean DEFAULT true,
    mandatory boolean DEFAULT false,                      -- curso obrigatório
    due_date character varying(10) DEFAULT '',            -- prazo YYYY-MM-DD (obrigatórios)
    points integer DEFAULT 50,                            -- pontos ao concluir (ranking)
    pass_score integer DEFAULT 70,                        -- nota mínima do quiz (%)
    quiz text DEFAULT '[]',                               -- JSON: [{q, options:[...], answer:idx}]
    created_at timestamp with time zone DEFAULT now()
);
CREATE INDEX ix_gov_courses_id ON public.gov_courses USING btree (id);

CREATE TABLE public.gov_course_progress (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id integer NOT NULL,
    user_email character varying(120) DEFAULT '',
    completed text DEFAULT '[]',                          -- JSON: lista de índices de aulas concluídas
    status character varying(20) DEFAULT 'Em andamento',  -- Em andamento | Concluído
    quiz_score integer DEFAULT -1,                        -- -1 = não realizado; 0..100
    quiz_passed boolean DEFAULT false,
    certificate_code character varying(40) DEFAULT '',    -- emitido ao concluir
    completed_at character varying(30) DEFAULT '',
    updated_at character varying(30) DEFAULT '',
    created_at timestamp with time zone DEFAULT now()
);
CREATE INDEX ix_gov_course_progress_id ON public.gov_course_progress USING btree (id);
CREATE INDEX ix_gov_course_progress_course_id ON public.gov_course_progress USING btree (course_id);
CREATE INDEX ix_gov_course_progress_user_email ON public.gov_course_progress USING btree (user_email);

-- Hardening (aplicado separadamente): RLS deny-by-default em todo o schema public.
-- DO $$ DECLARE t text; BEGIN
--   FOR t IN SELECT tablename FROM pg_tables WHERE schemaname='public' LOOP
--     EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
--   END LOOP; END $$;
